// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNXFRBEEANyFXfgAOuXkTiV5VPl_rtedg',
    appId: '1:249262630407:web:269d45c7c8b8a432e52ca2',
    messagingSenderId: '249262630407',
    projectId: 'sales-system-d49b4',
    authDomain: 'sales-system-d49b4.firebaseapp.com',
    storageBucket: 'sales-system-d49b4.firebasestorage.app',
    measurementId: 'G-RJYC5FRNEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZx-5-05_yPufvD5ETBQESfOsiTgcC_1o',
    appId: '1:249262630407:android:efbc54e798b7f0fee52ca2',
    messagingSenderId: '249262630407',
    projectId: 'sales-system-d49b4',
    storageBucket: 'sales-system-d49b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDElcMM5vYGyLzbQ8sS1hGOKdkFgD0EzzI',
    appId: '1:249262630407:ios:9be94f7d9605c4b2e52ca2',
    messagingSenderId: '249262630407',
    projectId: 'sales-system-d49b4',
    storageBucket: 'sales-system-d49b4.firebasestorage.app',
    iosBundleId: 'com.example.salesMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDElcMM5vYGyLzbQ8sS1hGOKdkFgD0EzzI',
    appId: '1:249262630407:ios:9be94f7d9605c4b2e52ca2',
    messagingSenderId: '249262630407',
    projectId: 'sales-system-d49b4',
    storageBucket: 'sales-system-d49b4.firebasestorage.app',
    iosBundleId: 'com.example.salesMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNXFRBEEANyFXfgAOuXkTiV5VPl_rtedg',
    appId: '1:249262630407:web:8067189f2b1a9f2be52ca2',
    messagingSenderId: '249262630407',
    projectId: 'sales-system-d49b4',
    authDomain: 'sales-system-d49b4.firebaseapp.com',
    storageBucket: 'sales-system-d49b4.firebasestorage.app',
    measurementId: 'G-SE2STR3H06',
  );
}
